// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransitAR.Structures;

#nullable disable

namespace TransitAR.Structures.Migrations
{
    [DbContext(typeof(TransitARContext))]
    partial class TransitARContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransitAR.Structures.Condicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Condiciones");
                });

            modelBuilder.Entity("TransitAR.Structures.ContactoPostulante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerfilPostulanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilPostulanteId", "Tipo")
                        .IsUnique();

                    b.ToTable("ContactoPostulantes");
                });

            modelBuilder.Entity("TransitAR.Structures.ContactoRefugio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RefugioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("RefugioId", "Tipo")
                        .IsUnique();

                    b.ToTable("ContactosRefugio");
                });

            modelBuilder.Entity("TransitAR.Structures.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("TransitAR.Structures.Mascota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CondicionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimientoAproximada")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotosUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Raza")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("RefugioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sexo")
                        .HasColumnType("int");

                    b.Property<int?>("Tamanio")
                        .HasColumnType("int");

                    b.Property<bool>("Vacunado")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RefugioId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("TransitAR.Structures.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("PostulacionId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("TransitAR.Structures.PerfilPostulante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CercaniaVeterinaria")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DetalleOtrasMascotas")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("ExperienciaPrevia")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("HorasSoloPorDia")
                        .HasColumnType("int");

                    b.Property<string>("MotivoPostulacion")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<bool>("PatioCerrado")
                        .HasColumnType("bit");

                    b.Property<int>("Seleccion")
                        .HasColumnType("int");

                    b.Property<bool>("TieneOtrasMascotas")
                        .HasColumnType("bit");

                    b.Property<bool>("TienePatio")
                        .HasColumnType("bit");

                    b.Property<string>("TipoVivienda")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("PerfilPostulantes");
                });

            modelBuilder.Entity("TransitAR.Structures.Postulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DisponibilidadFecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisponibilidadHorario")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPostulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PublicacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PublicacionId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Postulaciones");
                });

            modelBuilder.Entity("TransitAR.Structures.Publicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotosUrlExtra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MascotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PlazoEstimado")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("TransitAR.Structures.Refugio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MensajeRechazoAutomatico")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Refugios");
                });

            modelBuilder.Entity("TransitAR.Structures.Seguimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("TenenciaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenenciaId");

                    b.ToTable("Seguimientos");
                });

            modelBuilder.Entity("TransitAR.Structures.Tenencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaConversion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinEstimada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FinalizoBien")
                        .HasColumnType("bit");

                    b.Property<Guid>("MascotaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Modalidad")
                        .HasColumnType("int");

                    b.Property<string>("ObservacionCierre")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("PostulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MascotaId");

                    b.HasIndex("PostulacionId")
                        .IsUnique();

                    b.ToTable("Tenencias");
                });

            modelBuilder.Entity("TransitAR.Structures.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("RefugioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int?>("RolRefugio")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TransitAR.Structures.ContactoPostulante", b =>
                {
                    b.HasOne("TransitAR.Structures.PerfilPostulante", null)
                        .WithMany("Contactos")
                        .HasForeignKey("PerfilPostulanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.ContactoRefugio", b =>
                {
                    b.HasOne("TransitAR.Structures.Refugio", null)
                        .WithMany("Contactos")
                        .HasForeignKey("RefugioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Mascota", b =>
                {
                    b.HasOne("TransitAR.Structures.Refugio", null)
                        .WithMany("Mascotas")
                        .HasForeignKey("RefugioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Mensaje", b =>
                {
                    b.HasOne("TransitAR.Structures.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitAR.Structures.Postulacion", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("PostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emisor");
                });

            modelBuilder.Entity("TransitAR.Structures.PerfilPostulante", b =>
                {
                    b.HasOne("TransitAR.Structures.Usuario", null)
                        .WithOne("Perfil")
                        .HasForeignKey("TransitAR.Structures.PerfilPostulante", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Postulacion", b =>
                {
                    b.HasOne("TransitAR.Structures.Publicacion", null)
                        .WithMany("Postulaciones")
                        .HasForeignKey("PublicacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Publicacion", b =>
                {
                    b.HasOne("TransitAR.Structures.Mascota", null)
                        .WithMany("Publicaciones")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Seguimiento", b =>
                {
                    b.HasOne("TransitAR.Structures.Tenencia", null)
                        .WithMany("Seguimientos")
                        .HasForeignKey("TenenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Tenencia", b =>
                {
                    b.HasOne("TransitAR.Structures.Mascota", null)
                        .WithMany("Tenencias")
                        .HasForeignKey("MascotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitAR.Structures.Postulacion", null)
                        .WithOne("Tenencia")
                        .HasForeignKey("TransitAR.Structures.Tenencia", "PostulacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TransitAR.Structures.Mascota", b =>
                {
                    b.Navigation("Publicaciones");

                    b.Navigation("Tenencias");
                });

            modelBuilder.Entity("TransitAR.Structures.PerfilPostulante", b =>
                {
                    b.Navigation("Contactos");
                });

            modelBuilder.Entity("TransitAR.Structures.Postulacion", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Tenencia");
                });

            modelBuilder.Entity("TransitAR.Structures.Publicacion", b =>
                {
                    b.Navigation("Postulaciones");
                });

            modelBuilder.Entity("TransitAR.Structures.Refugio", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("TransitAR.Structures.Tenencia", b =>
                {
                    b.Navigation("Seguimientos");
                });

            modelBuilder.Entity("TransitAR.Structures.Usuario", b =>
                {
                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
